apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
spec:
  provider: aws
  parameters:
    usePodIdentity: "true"
    objects: |
      - objectName: "{{ .Values.secretProviderClass.objectName }}"    # Your secret name in AWS Secrets Manager
        objectType: "secretsmanager"                                  # Indicates that the object is a secret from AWS Secrets Manager
